#
# Сначало в ручную 
#   #docker build -t hardunit:v1 .
#

services:
  login-hard:  # сменить
    image: hardunit:v1    
    container_name: (name) # поф
    restart: always
      #volumes:
      #- ./wg:/etc/wireguard
      #- ./app:/app
    environment:
      LOGIN: (login)  # логин пользователя
      W_PORT: (port)   # Порт для конфига клиета
      W_HOST: ru.darksurf.ru  # wg-хост
      DATABASE: ${DATABASE}  # база данных 
      WG_LAN: '10.8.0.0/24' # ЛАН wg
      TABLE: server_ru
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
#      - net.ipv4.conf.eth0.route_localnet=1
    networks:
      - hard_net
        #  ipv4_address: 172.30.0.2
    ports:
      - 45.142.122.244:(P O R T):51820/udp # PORT
networks:
  hard_net:
    name: hard_net
    driver: bridge
    enable_ipv6: false
    driver_opts:
      com.docker.network.bridge.name: hard_net
        #external: true
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1

