#  .env
# KEY=''
# DATABASE='postgresql://username:password@ip:port/db-name'
#
#
services:
  hardgate:
    build: . 
    container_name: hardgate
    restart: always
      #command: python app.py
    command: gunicorn -w 2 -b 0.0.0.0:5050 app:app
    environment:
      DATABASE: ${DATABASE} # .env
    
